brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"

imports_granularity = "Crate"
group_imports = "StdExternalCrate"

enum_discrim_align_threshold = 40
struct_field_align_threshold = 40

combine_control_expr = false
match_block_trailing_comma = true

format_strings = true

format_code_in_doc_comments = true

format_macro_matchers = true

comment_width = 60
wrap_comments = true
