[package]
name = "yary"
version = "0.1.0"
authors = ["Bazaah <github@luxolus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"

atoi = "0.4"

[dev-dependencies]
pretty_assertions = "0.7"
